### ISSUE TITLE
Syslog object is bound to random udp port

### ISSUE THREAD

**Issue by Mido22** [myndzi/udp-streams2#1]
Whenever a new Syslog2 object of type 'udp' gets created, I noticed that the system starts listening to a random port. Caused by below line.

https://github.com/myndzi/udp-streams2/blob/2a7ff2baa337ae118853cf091b2d7875e4113bd5/index.js#L86

This is happening because we are not binding the socket server to any port, leading nodejs to chose random port and bind to it [Source](https://nodejs.org/api/dgram.html#dgram_socket_bind_options_callback).

This might lead to unexpected system behavior and is possibly a security vulnerability.

**Comment by myndzi** [comment]
The socket is only ever used for transmitting (not receiving) data. I'm not sure about the technical underlying details (whether a receiving port *must* be bound in order to send data), but if anything this seems like a problem with the Node API, which specifies that [a port is opened when you call .bind](https://nodejs.org/api/dgram.html#dgram_dgram_createsocket_options_callback) (which I never do), not before.

I'm not sure what the vulnerability would be, here, but choosing a specific port instead of a random one doesn't improve matters in any tangible way, and selecting a random port ensures we get one, instead of potentially conflicting with one that's already open.

**Comment by myndzi** [comment]
[this code](https://github.com/nodejs/node/blob/master/lib/dgram.js#L439) in dgram.js is responsible for binding the socket if it isn't bound, which I guess must be required to send data

**Comment by Mido22** [comment]
Yeah, I understand, not really sure how to solve this issue in this project. Just that an udp port made for sending packets is listening to stuff and that too on `0.0.0.0` bothers me. Closing the issue, and thanks for creating/maintaining this awesome 'syslog2' module :)

**Comment by myndzi** [comment]
I could make it bind to 127.0.0.1, maybe? I'd have to test/verify that it can send to anywhere. It also doesn't hurt me anything to supply an option to let you choose a port, I just don't see much point really

**Comment by Mido22** [comment]
thought of something similar, but to bind with localhost, one would also have to bind a port, then logic has to be added so check for port collision. You are right about it not making much sense to give option to bind port when all it does is transmit.

How about this solution:

```
try { 
  self.socket = dgram.createSocket(opts.type);
  self.socket.on('listening', () => {
    var address = self.socket.address();
    self.socket.bind(address.port, '127.0.0.1');
  });
} 
```

**Comment by myndzi** [comment]
I don't think that works as written; it's already bound at the point that `.address` returns a value. Port is optional, but it seems a little hacky to explicitly bind to localhost on a random port just to avoid receiving packets we'll discard :\

**Comment by Mido22** [comment]
oh, now I get it. You meant something like:  `self.socket.bind({address: '127.0.0.1'})`

**Comment by myndzi** [comment]
After some testing, it appears that you can't send over a different interface than you're listening on, which makes sense. So, you can't use this to bind to 127.0.0.1 but send to the public internet, for example. I suggest just using a firewall I guess, which you should probably be doing anyway :)
